const GET_TICKETS_REQUEST = "GET_TICKETS_REQUEST";
const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
const GET_TICKETS_FAILURE = "GET_TICKETS_FAILURE";

export { GET_TICKETS_REQUEST, GET_TICKETS_FAILURE, GET_TICKETS_SUCCESS };
